### PR TITLE
Alvaro

### PR DESCRIPTION
**Pull request by alvarolazo**

### CODE REVIEW

**Comment by senoh1** [comment]
Are you still working on this?

**Comment by hayati01** [comment]
Actually not, but i received some pull requests from Alvaro. Then i merged
them. it looks better now.

Senaid ***@***.***>, 7 Kas 2024 Per, 23:08 tarihinde şunu
yazdı:

**Comment by alvarolazo** [comment]
it was my last try guys, it didn't work...

________________________________

**Comment by senoh1** [comment]
Ihor suggested to delete your branch

**Comment by senoh1** [comment]
I just did it now

**Comment by senoh1** [comment]
Alvaro did you try to push .gitignore folder?

**Comment by alvarolazo** [comment]
I didn't

________________________________

**Comment by senoh1** [comment]
@hayati01 Ozan I can see that you merged some changes into main

**Comment by alvarolazo** [comment]
You know, we need something like this to work during the week, some group task very light

Alvaro Lazo
________________________________

**Comment by senoh1** [comment]
I would help

**Pull request merged**
